// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhcc_aRiYlWV2xpQkqWQpS98HxjCKldb0',
    appId: '1:428819832661:android:e6cc1ecd100113c786d9dc',
    messagingSenderId: '428819832661',
    projectId: 'deshi-mart-8151c',
    storageBucket: 'deshi-mart-8151c.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtIAyMFgf_39pX2YFbg0xBsolI5F-9SSg',
    appId: '1:428819832661:web:37700c84ecdab46e86d9dc',
    messagingSenderId: '428819832661',
    projectId: 'deshi-mart-8151c',
    authDomain: 'deshi-mart-8151c.firebaseapp.com',
    storageBucket: 'deshi-mart-8151c.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6nz0dhO585inm_z-n9S3x1R4XUZjuBYA',
    appId: '1:428819832661:ios:c67580d85670d01a86d9dc',
    messagingSenderId: '428819832661',
    projectId: 'deshi-mart-8151c',
    storageBucket: 'deshi-mart-8151c.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6nz0dhO585inm_z-n9S3x1R4XUZjuBYA',
    appId: '1:428819832661:ios:c67580d85670d01a86d9dc',
    messagingSenderId: '428819832661',
    projectId: 'deshi-mart-8151c',
    storageBucket: 'deshi-mart-8151c.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtIAyMFgf_39pX2YFbg0xBsolI5F-9SSg',
    appId: '1:428819832661:web:a3f8d874cdfa3dc486d9dc',
    messagingSenderId: '428819832661',
    projectId: 'deshi-mart-8151c',
    authDomain: 'deshi-mart-8151c.firebaseapp.com',
    storageBucket: 'deshi-mart-8151c.firebasestorage.app',
  );

}